services:
  - type: web
    name: lexi-dcdrc-api
    env: python
    plan: free
    region: oregon
    branch: main
    rootDir: ""  # empty because root is project root
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    pythonVersion: 3.11
